# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyledger_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyledger_message.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16pyledger_message.proto\"\'\n\x11\x41\x63tivationRequest\x12\x12\n\nclient_key\x18\x01 \x01(\t\"&\n\x12\x41\x63tivationResponse\x12\x10\n\x08\x61uth_key\x18\x01 \x01(\t\"M\n\x15\x41uthenticationRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x17\n\x0fhashed_password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\",\n\x16\x41uthenticationResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\"I\n\x13SubscriptionRequest\x12\x12\n\nclient_key\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\":\n\x14SubscriptionResponse\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x13\n\x0bsession_key\x18\x02 \x01(\t\"Y\n\x0fPyledgerRequest\x12\x0c\n\x04\x63\x61ll\x18\x01 \x01(\t\x12\x12\n\nclient_key\x18\x02 \x01(\t\x12\x13\n\x0bsession_key\x18\x03 \x01(\t\x12\x0f\n\x07request\x18\x04 \x01(\x0c\"F\n\x10PyledgerResponse\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x10\n\x08response\x18\x03 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTIVATIONREQUEST = _descriptor.Descriptor(
  name='ActivationRequest',
  full_name='ActivationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_key', full_name='ActivationRequest.client_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=65,
)


_ACTIVATIONRESPONSE = _descriptor.Descriptor(
  name='ActivationResponse',
  full_name='ActivationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth_key', full_name='ActivationResponse.auth_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=105,
)


_AUTHENTICATIONREQUEST = _descriptor.Descriptor(
  name='AuthenticationRequest',
  full_name='AuthenticationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='AuthenticationRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hashed_password', full_name='AuthenticationRequest.hashed_password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='AuthenticationRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=184,
)


_AUTHENTICATIONRESPONSE = _descriptor.Descriptor(
  name='AuthenticationResponse',
  full_name='AuthenticationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='successful', full_name='AuthenticationResponse.successful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=230,
)


_SUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='SubscriptionRequest',
  full_name='SubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_key', full_name='SubscriptionRequest.client_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='SubscriptionRequest.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='SubscriptionRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=305,
)


_SUBSCRIPTIONRESPONSE = _descriptor.Descriptor(
  name='SubscriptionResponse',
  full_name='SubscriptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='SubscriptionResponse.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='SubscriptionResponse.session_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=365,
)


_PYLEDGERREQUEST = _descriptor.Descriptor(
  name='PyledgerRequest',
  full_name='PyledgerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='call', full_name='PyledgerRequest.call', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_key', full_name='PyledgerRequest.client_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='PyledgerRequest.session_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request', full_name='PyledgerRequest.request', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=456,
)


_PYLEDGERRESPONSE = _descriptor.Descriptor(
  name='PyledgerResponse',
  full_name='PyledgerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='PyledgerResponse.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PyledgerResponse.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='PyledgerResponse.response', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=528,
)

DESCRIPTOR.message_types_by_name['ActivationRequest'] = _ACTIVATIONREQUEST
DESCRIPTOR.message_types_by_name['ActivationResponse'] = _ACTIVATIONRESPONSE
DESCRIPTOR.message_types_by_name['AuthenticationRequest'] = _AUTHENTICATIONREQUEST
DESCRIPTOR.message_types_by_name['AuthenticationResponse'] = _AUTHENTICATIONRESPONSE
DESCRIPTOR.message_types_by_name['SubscriptionRequest'] = _SUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['SubscriptionResponse'] = _SUBSCRIPTIONRESPONSE
DESCRIPTOR.message_types_by_name['PyledgerRequest'] = _PYLEDGERREQUEST
DESCRIPTOR.message_types_by_name['PyledgerResponse'] = _PYLEDGERRESPONSE

ActivationRequest = _reflection.GeneratedProtocolMessageType('ActivationRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVATIONREQUEST,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:ActivationRequest)
  ))
_sym_db.RegisterMessage(ActivationRequest)

ActivationResponse = _reflection.GeneratedProtocolMessageType('ActivationResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVATIONRESPONSE,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:ActivationResponse)
  ))
_sym_db.RegisterMessage(ActivationResponse)

AuthenticationRequest = _reflection.GeneratedProtocolMessageType('AuthenticationRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATIONREQUEST,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticationRequest)
  ))
_sym_db.RegisterMessage(AuthenticationRequest)

AuthenticationResponse = _reflection.GeneratedProtocolMessageType('AuthenticationResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATIONRESPONSE,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticationResponse)
  ))
_sym_db.RegisterMessage(AuthenticationResponse)

SubscriptionRequest = _reflection.GeneratedProtocolMessageType('SubscriptionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIPTIONREQUEST,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:SubscriptionRequest)
  ))
_sym_db.RegisterMessage(SubscriptionRequest)

SubscriptionResponse = _reflection.GeneratedProtocolMessageType('SubscriptionResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIPTIONRESPONSE,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:SubscriptionResponse)
  ))
_sym_db.RegisterMessage(SubscriptionResponse)

PyledgerRequest = _reflection.GeneratedProtocolMessageType('PyledgerRequest', (_message.Message,), dict(
  DESCRIPTOR = _PYLEDGERREQUEST,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:PyledgerRequest)
  ))
_sym_db.RegisterMessage(PyledgerRequest)

PyledgerResponse = _reflection.GeneratedProtocolMessageType('PyledgerResponse', (_message.Message,), dict(
  DESCRIPTOR = _PYLEDGERRESPONSE,
  __module__ = 'pyledger_message_pb2'
  # @@protoc_insertion_point(class_scope:PyledgerResponse)
  ))
_sym_db.RegisterMessage(PyledgerResponse)


# @@protoc_insertion_point(module_scope)
